spring:
  application:
    name: config-server
  profiles:
    active:
        git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kopn9k/configurations

server:
  port: 8071

#Enable health and refresh Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true