spring:
  application:
    name: config-server
  profiles:
    active:
        git
  cloud:
    config:
      server:
        git:
          strictHostKeyChecking: false
          uri: https://github.com/kopn9k/configurations
          ignore-local-ssh-settings: true
          private-key: "-----BEGIN RSA PRIVATE KEY-----
  MIIJJwIBAAKCAgEAsHZL/Z7Rxzmdj75F6fkI8GcGwEXoE42ZLwCUFM6m981e8oRC
  qWWDFaIxm+ouPeh31yi0129OwsXwCrOtioFcw2JYxLyPXLA3kYkpx1qRjxwhqCgR
  9s25ysdX7TZLm3jMnVJgj95bihsQ9R5Ytjigm8FjnG9Evg3D3QKe+6yhtn4vdKU0
  zy8dXxRUhfZTwAAy5ga0EqJ0f9qv/w5dpZTRVxy1CUa5ZwM5QBA31dAC3FWkx3WA
  Jofk+yv7OwtfYRxpqLSBanw0LUCaxvvgeJGtSK/AzQ++Rwn0lPhQcZjERZH2DUkZ
  i5zmQRNFp1bHlNexq+OSmyZrZTpQNj+QcvChvioSM1BOuK4JxFN0DllkvQBO+UUE
  0HsRw+3yZT52Npk5o/90gVvfn7UeZxemEe+W+wSkBGlmN3P5xNofFR/YHbr+dAwI
  ENrHg6ULn94H9+XmsPg+JNQxXqTgdNO2E2IsiZKebcyaLgCcU8pLzriLmbU72R2t
  RRkCxoIPKZojyGT+2SkhOy354/e4sTC0om/0RXq1+EJCpMa61ytI0K9C7TPf5Nkl
  9T6SFfylzK6QhY4Ql66XlrPf2sQTR6nUCtB15G8VUwGO/R/DlEy/4/81OMfrDWaX
  raKKv6cc9C6E98GYg3i0F6EHUYvaxGw8i4Gw5nFsjyLKbJWV6Pm9NUhs+GsCAwEA
  AQKCAgAF+uxWWwSG+OfjEDK0XDE2XHd5GqVjzD+tvRpHnj1AVqBqHZtYvEz19boy
  q3wHsxIko4eFaYtExIp/AlnWQM4Q/Qs/F5jQLlSjxP86d1JJhE2LslfxgkVSnvDW
  5Ckpyq08g6csGQAHLSWk+PNOsZqXzLUAfzDYNAU4Pzd+FfqhAaPAEz037EPVjg3T
  QGbUMe2HqCCAJStHjfS68xSvYNy7VAi6mL/9wrk095e80kDWkLx12gCOzbov3Oy1
  sov38YuPIRblsfHeurrEFZMk4uL5fKNPD8KGC8tTJRsszl2QcgLhrmGEPrv65plM
  s38uByVJSvwT7/hhxNklDYBqtMb2aWFzXjTzDxYDjOO9fyRewOsQbLj0rPQ4n1De
  e4bMLgYddYC2M+GXUp1Cx0ff5O7mSiC0wjvm3NhQriGiZgPGcgkRR5rZILJpuKZT
  sxx8p7Q+H6yW2GwZzBM1XR9dQifTxICzU3XKY6KTi8em9m839rSMEvmchfHBDb0d
  UpwrJhNTBGOd2FYcygHNs9Chv8o6XPl8Jc57LrIYVXFk341OVgc42cxGgxM+Zwg7
  +6OpRCx2HgEwAbyJ5xPOVoSSUM3MGpr25XbhYpSeX8VUEnExuK4VMqfiEVcj2B2K
  4KzWrXQP5Gya0t5P34Hj6AgpNqh84BQD9dfhuexQVVBBRxc9wQKCAQEAv++ikZtI
  bT4u2muzSeA+nehqAlf8qUPnBxVIP0y4arV1myocgUOjL6ziMhZVvNu8r3vJul9m
  YC0gcy3g/2pLG+rIYL6BPsY0KoivV1x/dmysbUuLuMDt39eycwEkGCJoof5VXZuz
  nWUdO9pEOm+7mbGIUFtzY2W944GKekWPUl9XPTzhIAu96QlzSv6n63lBaoRTzN31
  Or/x4IkdJpx2QuIrI8d2bkdDDM9dmj+/ZO9tYB5HVYBCZFn77AjYG7jNBgUIOkBx
  jbC4kfJQfya8lvXHaMicbvmgBdPBtF5NSR6xCyWsdnBwo6g5lTXSOa7yZlbYrb71
  UepipBKcL1WkywKCAQEA61x05AJ6gekiGvG4NP5W0NgN9aKja1jN2wzbBT0fHCfM
  sURRpuE8eAFwFj4bxg/SNmHfv27jbvPFbmXnhFejnaJyEz19OD1uBCFi7p2qcBCS
  U4n+iaMhkD4w4JCyt0yk/mcs0RHcFPSvbTmNer7N3T0613/AeJtrkuRoZ/dgz3w5
  6jSMUI6yNDEtV+X6eAjjMJm2D22P8bnEucdjM5CxV2VcdUSkANiofPY+ruy8f2DB
  0v3ckzdo7f4Pa9oWE9FjcBY6XJlA06h5tf8K0wP6MEoBjhv60Igcmo5bI9n5n3cE
  DOiGqOcEMszVFBusZIMaIVfelcw8YyHe5l6SQfMm4QKCAQB7kPtIYoAuVGo1lEDI
  vuWRI5+cAqlXD7Acj0cD+ZCAonIkguf3EGRuvQ6i0F5CR/UhxMAKjICMSoEppc/E
  n9nbDzwRjJQIpfHPsE+yHoqw4yXe91PsjciW43avM3zZTM2v/N1YdnUcT4ySi+KA
  /I36VKE9mqKey1GEtlFAhqfOkDLJ6ffFecm5zau8DFZu8pF60dZhfkPynsBJnfx2
  byRzysebMT69oIM6LAZG1+OQR9RSnSuvj/MuSAA35Tm8Hy1fQr4ZQoPYhH1O+IF6
  WqXvSiwm+YA8sdij58A9Lrjy6h9w3cA6QAlEU3k+5neBS3AjEqZMtTOamRsIJjMH
  BkwhAoIBADuatYuMySOfO+Dg+EqLYscPADIF1yb3XWKtFcZ03S0PMzptV9RQVDT8
  ADvRzMzS8uSM0tIzLevKVmSH8CLG4wunuQYAW3bjr7niDqDpUuGAgN4hI1IN+xEB
  fvVQD8J16Y736BSmVjsEYGzj112PdqkhuYYbt02T5qFTsNErh9vj1PLoDeTUznKD
  Rb1t44mEjqyfMMklcP/BkP2PbiL/8Ll2VPzpvjLsq3bCEcvQ7ke/5DYfzj2GGc+z
  uIoSt+aa73jSWENdGFrB3tjlVwNrjW+vPkeT9GfdIIlPpeslZ58nz+HI/VlG7/xB
  fXDTNUxbG0H4c8kx6NUeHcnvh1CmWGECggEAe+77hetOICkoYeGQZBghKSOkEEXo
  ffrhhiBQi/hezDNHucjW2yD359lsjNyh2N/RxIbNobo8XrxNSKR533QcH1khYz3a
  gEuHS4Xzh3INpPpf0U0vliTBdXhHyk/bZOQ54GygUUDbtJsWIYHfqE43OkOXRshQ
  6BTIOBQ6UVwM5rhXbwO/+ilU2F4fJP5rUeaVjFhz3n6xk0fdbgIoYM0wkf3++GQy
  2O0M+LnxMOHHSTZ1ioRPtP9osTKmJmrhAnneNyr48FeU215w4SY3iHidSn1OLVEp
  qMzp7hd9LW0J9I69CprDEUFdWGZSvLXhstNI4fAb/miwwowRQ/lRjgDivQ==
  -----END RSA PRIVATE KEY-----"

server:
  port: 8071

#Enable health and refresh Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true