version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ogrowth/configuration-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 3s
    environment:
      THC_PATH: "/actuator/health"
      THC_PORT: "8071"
      ENCRYPT_KEY: "IMSYMMETRIC"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: ogrowth/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    healthcheck:
      test: "/cnb/process/health-check"
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 3s
    environment:
      THC_PATH: "/actuator/health"
      THC_PORT: "8070"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
  gatewayserver:
    image: ogrowth/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8071"
      EUREKASERVER_URI: "http://eurekaserver:8070/eureka/"
      EUREKASERVER_PORT: "8070"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "gateway"
#  redisserver:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#    networks:
#      backend:
#        aliases:
#          - "redis"
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
  kafkaserver:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      backend:
        aliases:
          - "kafka"
  licensingservice:
    image: ogrowth/license-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      kafkaserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
  organizationservice:
    image: ogrowth/organization-service:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8071"
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      kafkaserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend


networks:
  backend:
    driver: bridge