spring:
  application:
    name: license-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://configserver:8071
logging:
  level:
      org.springframework.web: WARN
      com.pasha: DEBUG

